// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type RegisterReq struct {
	Email    string `json:"email"`    // 邮箱
	Password string `json:"password"` // 密码
	Code     string `json:"code"`     // 验证码
	Nickname string `json:"nickname"` // 昵称
}

type RegisterResp struct {
}

type SendCodeReq struct {
	Email string `json:"email"` // 邮箱地址
	Type  string `json:"type"`  // 验证码类型: register/reset_password/bind_email
}

type SendCodeResp struct {
	RetryAfter int `json:"retryAfter"` // 多少秒后可重发
}

type VerificationCodeMessage struct {
	Code      string `json:"code"`      // 验证码
	Receiver  string `json:"receiver"`  // 接收方邮箱
	Type      string `json:"type"`      // 验证码类型（注册/登录/重置密码）
	Timestamp int64  `json:"timestamp"` // 时间戳，用于过期判断
}
