// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码
	Code        string `json:"code"`        // 验证码
}

type ChangePasswordResp struct {
}

type JWK struct {
	Kty string `json:"kty"` // 密钥类型，如 RSA
	Kid string `json:"kid"` // 密钥标识符
	Use string `json:"use"` // 用途，sig 表示签名
	N   string `json:"n"`   // RSA 模数 (base64url 编码)
	E   string `json:"e"`   // RSA 指数 (base64url 编码)
	Alg string `json:"alg"` // 算法，如 RS256
}

type JWKSResp struct {
	Keys []JWK `json:"keys"` // 公钥列表
}

type LoginReq struct {
	Email      string `json:"email"`      // 邮箱
	Password   string `json:"password"`   // 密码
	RememberMe bool   `json:"rememberMe"` // 记住我
}

type LoginResp struct {
	ExpiresIn int64 `json:"expiresIn"` // AccessToken 有效期，单位:秒
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RefreshTokenReq struct {
}

type RefreshTokenResp struct {
	ExpiresIn int64 `json:"expiresIn"` // AccessToken 有效期，单位:秒
}

type RegisterReq struct {
	Email    string `json:"email"`    // 邮箱
	Password string `json:"password"` // 密码
	Code     string `json:"code"`     // 验证码
	Nickname string `json:"nickname"` // 昵称
}

type RegisterResp struct {
}

type ResetPasswordReq struct {
	Email    string `json:"email"`    // 邮箱
	Password string `json:"password"` // 新密码
	Code     string `json:"code"`     // 验证码
}

type ResetPasswordResp struct {
}

type SendVerifyCodeReq struct {
	Email string `json:"email"` // 邮箱地址
	Type  string `json:"type"`  // 验证码类型: register/reset_password/bind_email
}

type SendVerifyCodeResp struct {
	RetryAfter int `json:"retryAfter"` // 多少秒后可重发
}

type VerificationCodeMessage struct {
	Code      string `json:"code"`      // 验证码
	Receiver  string `json:"receiver"`  // 接收方邮箱
	Type      string `json:"type"`      // 验证码类型（注册/登录/重置密码）
	Timestamp int64  `json:"timestamp"` // 时间戳，用于过期判断
}
