// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "user/internal/handler/user"
	user_noauth "user/internal/handler/user_noauth"
	"user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ChangePasswordLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/changepassword",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.NoAuthLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: user_noauth.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user_noauth.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resetpassword",
					Handler: user_noauth.ResetPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/verifycode",
					Handler: user_noauth.SendVerifyCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user/v1/noauth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RefreshTokenLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/refreshtoken",
					Handler: user_noauth.RefreshTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user/v1/noauth"),
	)
}
