// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	account_noauth "user/internal/handler/account_noauth"
	"user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: account_noauth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: account_noauth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resetpassword",
				Handler: account_noauth.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verifycode",
				Handler: account_noauth.SendVerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/account/v1/noauth"),
	)
}
